---
title: "COVID Analysis"
author: "Kim Jisoo"
date: '2021 11 23 '
output: 
  pdf_document: 
    latex_engine: xelatex
    keep_tex: yes
---


```{r}
library(dslabs)
library(dplyr)
library(readxl)
library(ggplot2)
```
```{r message=FALSE, warning=FALSE}
adverse <- read_excel("C:/Users/user/Desktop/2021VAERSData/2021VAERSDATA2.xlsx")
raw_adverse <- adverse
```

1.
1)sex
```{r}
table(is.na(adverse$SEX))

adverse%>%filter(SEX=="F"|SEX=="M")%>%group_by(SEX)%>%summarise(n=n())%>%
  ggplot(aes(x=SEX,y=n,fill=SEX))+geom_bar(stat="identity")+labs(x="Sex",y="Frequency")

```
2)age
```{r}
table(is.na(adverse$CAGE_YR))
adverse%>%filter(!is.na(CAGE_YR))%>%ggplot(aes(x=CAGE_YR))+geom_histogram(col="black")+labs(x="Age")
adverse%>%filter(!is.na(CAGE_YR),SEX=="F"|SEX=="M")%>%
  ggplot(aes(y=SEX,x=CAGE_YR,fill=SEX))+geom_boxplot()+labs(x="Age")

```
3)symptom
```{R}
adverse$SYMPTOM=case_when(adverse$DIED=="Y"~"died",
                          adverse$L_THREAT=="Y"~"life_threat",
                          adverse$HOSPITAL=="Y"~"hospital",
                          adverse$DISABLE=="Y"~"disable")
t_symptom=table(adverse$SYMPTOM)
df <- data.frame(symptom=c("died","life_threat","hospital","disable"),
                 frequency=c(8536,6396,29933,9614))
bp <- ggplot(df,aes(x="",y=frequency,fill=symptom))+geom_bar(stat="identity")
(pie <- bp+coord_polar("y",start=0))


adverse%>%filter(!is.na(CAGE_YR),SEX=="F"|SEX=="M",!is.na(SYMPTOM))%>%
  ggplot(aes(y=SEX,x=CAGE_YR,fill=SEX))+geom_boxplot()+facet_grid(SYMPTOM~.)+labs(x="Age",y="")
             
```

2.
```{R}
vaccine <- read.csv("C:/Users/user/Desktop/country_vaccinations.csv")
library(lubridate)
```

1)how many people get fully vaccinated

```{r}
vac1 <- vaccine%>%mutate(week=week(date))%>%
  group_by(week)%>%summarise(n=sum(people_fully_vaccinated_per_hundred,na.rm=T))
vac1
vac2 <- vac1[(vac1$week<=46),]  
vac2%>%ggplot(aes(x=week,y=n))+
  geom_line()+
  labs(title="People Fully Vaccinated per 100",y="")
```
2)which country get fully vaccinated?
```{r}
GDP<- read.csv("C:/Users/user/Desktop/GDP.csv")
gdp2015 <- GDP%>%select(country,X2015)
recent_gapminder <- gapminder%>%filter(year==2015)
gapminder2015 <- inner_join(gdp2015,recent_gapminder,by="country")
gapminder2015 <- gapminder2015%>%rename("Gdp"="X2015")%>%select(-gdp)
vac3 <- vaccine%>%group_by(country)%>%summarise(fully_vaccinated=max(people_fully_vaccinated,na.rm=T))
df <- inner_join(vac3,gapminder2015,by="country")
```

```{r}
df2 <- df%>%mutate(fully_vaccinated_perCap=fully_vaccinated/population,gdp_perCap=Gdp/population)%>%select(fully_vaccinated_perCap,fully_vaccinated,Gdp,gdp_perCap,infant_mortality,life_expectancy,fertility,population)
pairs(df2)
cor(df2)
```

```{R}
df3 <- df%>%mutate(fully_vaccinated_perCap=fully_vaccinated/population,gdp_perCap=Gdp/population)
```

```{R}
df3%>%ggplot(aes(x=life_expectancy,y=fully_vaccinated_perCap))+geom_point(aes(col=continent))+geom_smooth(method="lm",col="black")
fitted = lm(fully_vaccinated_perCap~life_expectancy,data=df3)
summary(fitted)
```
```{r}
df3%>%ggplot(aes(x=Gdp,y=fully_vaccinated_perCap))+geom_point(aes(col=continent))+scale_x_log10()+geom_smooth(method="lm",col="black")
fitted2 = lm(fully_vaccinated_perCap~log(Gdp),data=df3)
summary(fitted2)
```
```{r}
fitted3 = lm(fully_vaccinated_perCap~life_expectancy+log(Gdp),data=df3)
summary(fitted3)
```



```{r}
fitted4=aov(fully_vaccinated_perCap~continent,data=df3)
summary(fitted4)
```
4.vaccine effect

```{r}
library(readr)
ftxo7ir2vr36cacqhg6m7gwbtbv6hy <- read_csv("https://query.data.world/s/ftxo7ir2vr36cacqhg6m7gwbtbv6hy")
covid <- ftxo7ir2vr36cacqhg6m7gwbtbv6hy
head(covid)
```

```{r}
library("RColorBrewer")
covid2 <- covid%>%mutate(week=week(date))%>%group_by(location,week)%>%summarise(w.case=sum(new_cases,na.rm=T))
covid2 
```  

```{r}
library(dslabs)
dat <- us_contagious_diseases%>%
  filter(!state%in%c("Hawaii","Alaska")&disease==the_disease)%>%
  mutate(rate=count/population*10000*52/weeks_reporting)%>%
  mutate(state=reorder(state,rate))
dat%>%ggplot(aes(year,state,fill=rate))+
  geom_tile(color="grey50")+
  scale_x_continuous(expand=c(0,0))+
  scale_fill_gradientn(colors=brewer.pal(9,"Reds"),trans="sqrt")+
  geom_vline(xintercept=1963,col="blue")+
  theme_minimal()+
  theme(panel.grid=element_blank(),
        legend.position = "bottom",
        text=element_text(size=8))+
  ggtitle(the_disease)+
  ylab("")+xlab("")
```

```{r}
set.seed(2019)
  covid2%>%filter(location%in%(sample(covid2$location,30,replace=F)))%>%ggplot(aes(x=week,y=location,fill=w.case))+
  geom_tile(color="grey50")+
  scale_fill_gradientn(colors=brewer.pal(9,"Reds"))+
  theme_minimal()+
  geom_vline(xintercept = 25,col="blue")+
  ggtitle("COVID9")+ylab("")+xlab("")+theme(legend.position = "bottom")
```




```{r}
top30 <-  df3%>%arrange(desc(fully_vaccinated_perCap))%>%select(country)%>%head(30)%>%pull()
covid2%>%filter(location%in%(top30))%>%ggplot(aes(x=week,y=location,fill=w.case))+
  geom_tile(color="grey50")+
  scale_fill_gradientn(colors=brewer.pal(9,"Reds"))+
  theme_minimal()+
  geom_vline(xintercept = 25,col="blue")+
  ggtitle("Covid Top30")+ylab("")+xlab("")+theme(legend.position = "bottom")
```
```{r}
covid3 <- covid2%>%filter(location%in%(top30))%>%mutate(after=ifelse(week>=25,"T","F"))

t.test(data=covid3, w.case~after)

```
